sudo: required

language: java

services:
  - docker

branches:
  only:
    - master
    - stable

install: true

script:
  - ./gradlew clean build -x test -x library:javadoc
  - ./gradlew library:test web-service:test web-service:jar

deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew library:bintrayUpload web-service:pushDockerImages
    on:
      branch: master
