apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: ilivalidator-template
  annotations:
    openshift.io/display-name: "All components for AGI avgbs2mtab Web Service"
    description: >-
      "Creates all necessary components for the AGI avgbs2mtab Web Service"
    openshift.io/long-description: >-
      "Creates all necessary components for the AGI avgbs2mtab Web Service"
    tags: "agi,gdi,avgbs2mtab,java"
    iconClass: icon-java
labels:
  application: avgbs2mtab
  env: ${env}
  createdBy: avgbs2mtab-template
parameters:
  - description: Name for Environment
    name: env 
    value: test
  - description: Version of Image
    name: version
    value:
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Image Stream of the application
    labels:
      application: avgbs2mtab-web-service-${env}  
    creationTimestamp: null
    generation: 1
    name: avgbs2mtab-web-service-${env}
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      application: avgbs2mtab-web-service-${env}
      deploymentconfig: avgbs2mtab-web-service-${env}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          application: avgbs2mtab-web-service-${env}
          deploymentconfig: avgbs2mtab-web-service-${env}
      spec:
        containers:
        - image: sogis/avgbs2mtab-web-service
          imagePullPolicy: IfNotPresent
          name: avgbs2mtab-web-service-${env}
          ports:
          - containerPort: 8878
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - avgbs2mtab-web-service-${env}
        from:
          kind: ImageStreamTag
          name: avgbs2mtab-web-service:${version}
          namespace: agi-avgbs2mtab
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    name: avgbs2mtab-service-${env}
    annotations:
      description: http port of application
    labels:
      application: avgbs2mtab-web-service-${env}
  spec:
    selector:
      application: avgbs2mtab-web-service-${env}
    ports:
    - protocol: TCP
      name: "80"
      port: 80
      targetPort: 8878
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: avgbs2mtab-web-service
  spec:
    tags:
    - from:
        kind: DockerImage
        name: sogis/avgbs2mtab-web-service:${version}
      name: ${version}
      importPolicy:
        scheduled: false
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/timeout: 120s
    labels:
      application: avgbs2mtab-web-service
      createdBy: ilivalidator-template
    name: avgbs2mtab-${env}
    namespace: agi-avgbs2mtab
  spec:
    host: avgbs2mtab-${env}.dev.so.ch
    port:
      targetPort: "80"
    to:
      kind: Service
      name: avgbs2mtab-service-${env}
      weight: 100
    wildcardPolicy: None
