name: CI/CD

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build with Gradle
        run: |
          ./gradlew clean build -x test -x library:javadoc
          ./gradlew library:test web-service:test web-service:jar
        env:
          BUILD_NUMBER: ${{ env.GITHUB_RUN_NUMBER }}
      - name: Push docker image
        run: |
          export CI_JOB_TIMESTAMP=$(date +%Y%m%dT%H%M%S)
          docker images
          ./gradlew web-service:pushDockerImages
        env:
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      